# Puerto del servidor
server.port=8080

# DataSource Configuration for SQLite
# Usamos 'classpath:erosion.db' para que Spring Boot encuentre la BD en target/classes
spring.datasource.url=jdbc:sqlite:classpath:erosion.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA and Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# Usamos 'validate' para asegurar que las tablas existen, pero no para modificarlas
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivamos la inicialización de data.sql si la BD ya está poblada
spring.sql.init.mode=never
# spring.sql.init.data-locations=classpath:data.sql