# Puerto del servidor
server.port=8080

# DataSource Configuration for SQLite
spring.datasource.url=jdbc:sqlite:src/main/resources/erosion.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA and Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicialización con data.sql
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql